In [157]:
#Importando a base de dados
import pandas as pd 
import numpy  as np
df = pd.read_csv("idep_2023.csv", sep=';', decimal=',', encoding='latin1', skiprows=1, header=0 , na_values=['-'])

df2 = pd.read_excel("idep_2024.xlsx", skiprows=1, header=0)

df_2023= df
df_2024 = df2

display(df_2023,df_2024)

,Cod_Esc,Escola,Diretoria,Distrito,NSE,Grupo,ICG,Faixa,IDEP_INICIAL,IDEP_FINAL,IDEP_INICIAL.1,IDEP_FINAL.1
0,92762,EMEF JOAO XXIII,BUTANTA,RAPOSO TAVARES,"49,81640282",2,6,4,4.0,2.3,4.5,3.9
1,94196,EMEF ERICO VERISSIMO,FREGUESIA/BRASILANDIA,FREGUESIA DO O,"50,00111797",2,3,3,4.4,2.7,4.6,3.6
2,94269,EMEF CASTRO ALVES,FREGUESIA/BRASILANDIA,BRASILANDIA,"46,35954027",1,5,2,4.1,2.7,3.7,3.5
3,94315,EMEF PEDRO AMERICO,FREGUESIA/BRASILANDIA,FREGUESIA DO O,"46,12330621",1,3,1,4.4,2.8,3.8,3.0
4,19351,"EMEF MARILI DIAS, PROFA",PIRITUBA,ANHANGUERA,"48,57506222",1,3,1,4.1,2.9,4.5,3.9
...,...,...,...,...,...,...,...,...,...,...,...,...
555,19496,EMEF PLINIO MARCOS,CAPELA DO SOCORRO,PARELHEIROS,"47,2417116",1,2,1,3.0,NaN,3.5,NaN
556,19526,EMEF DONATO SUSUMU KIMURA,CAMPO LIMPO,CAPAO REDONDO,"48,01412351",1,1,1,4.6,NaN,NaN,NaN
557,19660,EMEF SETE PRAIAS,SANTO AMARO,PEDREIRA,"45,82469921",1,2,1,4.4,NaN,NaN,NaN
558,19677,EMEF P FOM LICEU,NaN,NaN,-,-,-,-,5.4,NaN,NaN,NaN
559,19712,"EMEF MARIA BERENICE DOS SANTOS, PROFA.",CAMPO LIMPO,JARDIM SAO LUI,"47,96323311",1,2,1,5.1,NaN,NaN,NaN

,Cod_Esc,Escola,Diretoria,Distrito,NSE,Grupo,ICG,Faixa,IDEP_INICIAL,IDEP_FINAL
0,19488,EMEF PAULO CARNEIRO THOMAZ ALVES. GEN.,JACANA/TREMEMBE,VILA MARIA,50.387,2,6,4,3.4,3.2
1,92622,EMEF ARLINDO CAETANO FILHO. PROF.,SAO MATEUS,SAPOPEMBA,47.039,1,3,1,4.5,3.2
2,94277,EMEF JOAO AMOS COMENIUS,FREGUESIA/BRASILANDIA,BRASILANDIA,47.224,1,3,1,4.2,3.2
3,18546,EMEF DAMIAO. FREI,CAPELA DO SOCORRO,GRAJAU,49.02,1,6,2,6.3,3.3
4,19220,EMEF MARIO LAGO,PIRITUBA,JARAGUA,48.977,1,6,2,6.2,3.3
...,...,...,...,...,...,...,...,...,...,...
550,19474,EMEF VARGEM GRANDE II,CAPELA DO SOCORRO,PARELHEIROS,47.828,1,2,1,5.9,NaN
551,19496,EMEF PLINIO MARCOS,CAPELA DO SOCORRO,PARELHEIROS,47.242,1,2,1,4.3,NaN
552,19660,EMEF SETE PRAIAS,SANTO AMARO,PEDREIRA,45.825,1,2,1,5.0,NaN
553,19712,EMEF MARIA BERENICE DOS SANTOS. PROFA.,CAMPO LIMPO,JARDIM SAO LUI,47.963,1,2,1,6.3,NaN
554,97705,EMEF AURELIANO LEITE,GUAIANASES,CIDADE TIRADEN,48.802,1,3,1,4.1,NaN

In [158]:
#Vendos as informaçoes 
df_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Cod_Esc         560 non-null    int64
 1   Escola          560 non-null    object
 2   Diretoria       559 non-null    object
 3   Distrito        559 non-null    object
 4   NSE             560 non-null    object
 5   Grupo           559 non-null    object
 6   ICG             560 non-null    object
 7   Faixa           559 non-null    object
 8   IDEP_INICIAL    560 non-null    float64
 9   IDEP_FINAL      550 non-null    float64
 10  IDEP_INICIAL.1  550 non-null    float64
 11  IDEP_FINAL.1    548 non-null    float64
dtypes: float64(4), int64(1), object(7)
memory usage: 52.6+ KB

In [159]:
df_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555 entries, 0 to 554
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Cod_Esc       555 non-null    int64
 1   Escola        555 non-null    object
 2   Diretoria     555 non-null    object
 3   Distrito      555 non-null    object
 4   NSE           555 non-null    object
 5   Grupo         555 non-null    object
 6   ICG           555 non-null    object
 7   Faixa         555 non-null    object
 8   IDEP_INICIAL  555 non-null    float64
 9   IDEP_FINAL    546 non-null    float64
dtypes: float64(2), int64(1), object(7)
memory usage: 43.5+ KB

In [160]:
#Valores Nulos de 2023  
df_2023.isnull().sum()

Cod_Esc            0
Escola             0
Diretoria          1
Distrito           1
NSE                0
Grupo              1
ICG                0
Faixa              1
IDEP_INICIAL       0
IDEP_FINAL        10
IDEP_INICIAL.1    10
IDEP_FINAL.1      12
dtype: int64

In [161]:
df_2024.isnull().sum()

Cod_Esc         0
Escola          0
Diretoria       0
Distrito        0
NSE             0
Grupo           0
ICG             0
Faixa           0
IDEP_INICIAL    0
IDEP_FINAL      9
dtype: int64

In [ ]:
# Exclui o Meu Valores nulos 
df_2024 = df_2024.dropna(subset=["IDEP_FINAL"])

df_2024.isnull().sum()

Cod_Esc         0
Escola          0
Diretoria       0
Distrito        0
NSE             0
Grupo           0
ICG             0
Faixa           0
IDEP_INICIAL    0
IDEP_FINAL      0
dtype: int64

In [163]:
# Exclui os valores  da base de 2023 

df_2023 = df_2023.dropna(subset=["IDEP_FINAL"])
df_2023 = df_2023.dropna(subset=["NSE"])
df_2023 = df_2023.dropna(subset=["IDEP_INICIAL"])

In [164]:
df_2024.info()

<class 'pandas.core.frame.DataFrame'>
Index: 546 entries, 0 to 545
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Cod_Esc       546 non-null    int64
 1   Escola        546 non-null    object
 2   Diretoria     546 non-null    object
 3   Distrito      546 non-null    object
 4   NSE           546 non-null    object
 5   Grupo         546 non-null    object
 6   ICG           546 non-null    object
 7   Faixa         546 non-null    object
 8   IDEP_INICIAL  546 non-null    float64
 9   IDEP_FINAL    546 non-null    float64
dtypes: float64(2), int64(1), object(7)
memory usage: 46.9+ KB

In [165]:
#Mudando os tipos de dados de 2024 

df_2024['NSE'] = pd.to_numeric(
    df_2024['NSE'].astype(str).str.replace(',', '.'),
    errors='coerce'
).round(2)
df_2024["Grupo"] = pd.to_numeric(df_2023["Grupo"], errors="coerce").astype("Int64")
df_2024["ICG"] = pd.to_numeric(df_2023["ICG"], errors="coerce")
df_2024["IDEP_FINAL"] = pd.to_numeric(df_2023["IDEP_FINAL"], errors="coerce")

C:\Users\igor_\AppData\Local\Temp\ipykernel_4348\4248052112.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2024['NSE'] = pd.to_numeric(
C:\Users\igor_\AppData\Local\Temp\ipykernel_4348\4248052112.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2024["Grupo"] = pd.to_numeric(df_2023["Grupo"], errors="coerce").astype("Int64")
C:\Users\igor_\AppData\Local\Temp\ipykernel_4348\4248052112.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2024["ICG"] = pd.to_numeric(df_2023["ICG"], errors="coerce")
C:\Users\igor_\AppData\Local\Temp\ipykernel_4348\4248052112.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2024["IDEP_FINAL"] = pd.to_numeric(df_2023["IDEP_FINAL"], errors="coerce")

In [ ]:
#Vendo se os dados estão da Maneira que eu queria 
df_2024.info()

<class 'pandas.core.frame.DataFrame'>
Index: 546 entries, 0 to 545
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Cod_Esc       546 non-null    int64
 1   Escola        546 non-null    object
 2   Diretoria     546 non-null    object
 3   Distrito      546 non-null    object
 4   NSE           543 non-null    float64
 5   Grupo         543 non-null    Int64
 6   ICG           543 non-null    float64
 7   Faixa         546 non-null    object
 8   IDEP_INICIAL  546 non-null    float64
 9   IDEP_FINAL    546 non-null    float64
dtypes: Int64(1), float64(4), int64(1), object(4)
memory usage: 47.5+ KB

In [167]:

#Visualizando os tipos de dados de 2023

df_2023.info()

<class 'pandas.core.frame.DataFrame'>
Index: 550 entries, 0 to 549
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Cod_Esc         550 non-null    int64
 1   Escola          550 non-null    object
 2   Diretoria       550 non-null    object
 3   Distrito        550 non-null    object
 4   NSE             550 non-null    object
 5   Grupo           549 non-null    object
 6   ICG             550 non-null    object
 7   Faixa           549 non-null    object
 8   IDEP_INICIAL    550 non-null    float64
 9   IDEP_FINAL      550 non-null    float64
 10  IDEP_INICIAL.1  546 non-null    float64
 11  IDEP_FINAL.1    548 non-null    float64
dtypes: float64(4), int64(1), object(7)
memory usage: 72.0+ KB

In [168]:
# Mudando os tipos de Dados da minha tabela de 2023 
df_2023['NSE'] = pd.to_numeric(
    df_2023['NSE'].astype(str).str.replace(',', '.'),
    errors='coerce'
).round(2)
df_2023["Grupo"] = pd.to_numeric(df_2023["Grupo"], errors="coerce").astype("Int64")
df_2023["ICG"] = pd.to_numeric(df_2023["ICG"], errors="coerce")
df_2023["IDEP_FINAL"] = pd.to_numeric(df_2023["IDEP_FINAL"], errors="coerce")

In [169]:
df_2023.info()

<class 'pandas.core.frame.DataFrame'>
Index: 550 entries, 0 to 549
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Cod_Esc         550 non-null    int64
 1   Escola          550 non-null    object
 2   Diretoria       550 non-null    object
 3   Distrito        550 non-null    object
 4   NSE             547 non-null    float64
 5   Grupo           547 non-null    Int64
 6   ICG             547 non-null    float64
 7   Faixa           549 non-null    object
 8   IDEP_INICIAL    550 non-null    float64
 9   IDEP_FINAL      550 non-null    float64
 10  IDEP_INICIAL.1  546 non-null    float64
 11  IDEP_FINAL.1    548 non-null    float64
dtypes: Int64(1), float64(6), int64(1), object(4)
memory usage: 72.6+ KB

In [170]:
#Mudando Os tipos de dados da minha tabeka 2024 

df_2024['NSE'] = pd.to_numeric(
    df_2024['NSE'].astype(str).str.replace(',', '.'),
    errors='coerce'
).round(2)
df_2024["Grupo"] = pd.to_numeric(df_2024["Grupo"], errors="coerce").astype("Int64")
df_2024["ICG"] = pd.to_numeric(df_2024["ICG"], errors="coerce")
df_2024["IDEP_FINAL"] = pd.to_numeric(df_2024["IDEP_FINAL"], errors="coerce")

C:\Users\igor_\AppData\Local\Temp\ipykernel_4348\3251356215.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2024['NSE'] = pd.to_numeric(
C:\Users\igor_\AppData\Local\Temp\ipykernel_4348\3251356215.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2024["Grupo"] = pd.to_numeric(df_2024["Grupo"], errors="coerce").astype("Int64")
C:\Users\igor_\AppData\Local\Temp\ipykernel_4348\3251356215.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2024["ICG"] = pd.to_numeric(df_2024["ICG"], errors="coerce")
C:\Users\igor_\AppData\Local\Temp\ipykernel_4348\3251356215.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2024["IDEP_FINAL"] = pd.to_numeric(df_2024["IDEP_FINAL"], errors="coerce")

In [171]:

display(df_2023)

,Cod_Esc,Escola,Diretoria,Distrito,NSE,Grupo,ICG,Faixa,IDEP_INICIAL,IDEP_FINAL,IDEP_INICIAL.1,IDEP_FINAL.1
0,92762,EMEF JOAO XXIII,BUTANTA,RAPOSO TAVARES,49.82,2,6.0,4,4.0,2.3,4.5,3.9
1,94196,EMEF ERICO VERISSIMO,FREGUESIA/BRASILANDIA,FREGUESIA DO O,50.00,2,3.0,3,4.4,2.7,4.6,3.6
2,94269,EMEF CASTRO ALVES,FREGUESIA/BRASILANDIA,BRASILANDIA,46.36,1,5.0,2,4.1,2.7,3.7,3.5
3,94315,EMEF PEDRO AMERICO,FREGUESIA/BRASILANDIA,FREGUESIA DO O,46.12,1,3.0,1,4.4,2.8,3.8,3.0
4,19351,"EMEF MARILI DIAS, PROFA",PIRITUBA,ANHANGUERA,48.58,1,3.0,1,4.1,2.9,4.5,3.9
...,...,...,...,...,...,...,...,...,...,...,...,...
545,93912,"EMEF CARLOS PASQUALE, PROF.",SAO MIGUEL,ITAIM PAULISTA,53.12,3,6.0,6,4.9,5.8,5.2,4.6
546,95125,EMEF BARTOLOMEU LOURENCO DE GUSMAO,ITAQUERA,CARRAO,54.34,3,3.0,5,5.0,5.8,4.6,5.3
547,93173,"EMEF JOAQUIM CANDIDO DE AZEVEDO MARQUES, DES.",SANTO AMARO,SANTO AMARO,54.80,3,3.0,5,5.3,5.9,6.0,5.1
548,92690,"EMEF AMORIM LIMA, DES.",BUTANTA,BUTANTA,57.80,3,3.0,5,5.9,6.1,5.1,4.8
549,108,"EMEF JOSE ERMIRIO DE MORAES, SEN.",SAO MIGUEL,JARDIM HELENA,48.15,1,3.0,1,4.8,6.8,4.4,4.4

In [172]:
#Excluir Colunas  de 2023 
df_2023 = df_2023.drop(["IDEP_INICIAL.1", "IDEP_FINAL.1"], axis=1)

In [173]:
#Criando Analises e colunas para base 2023
display(df_2023)

,Cod_Esc,Escola,Diretoria,Distrito,NSE,Grupo,ICG,Faixa,IDEP_INICIAL,IDEP_FINAL
0,92762,EMEF JOAO XXIII,BUTANTA,RAPOSO TAVARES,49.82,2,6.0,4,4.0,2.3
1,94196,EMEF ERICO VERISSIMO,FREGUESIA/BRASILANDIA,FREGUESIA DO O,50.00,2,3.0,3,4.4,2.7
2,94269,EMEF CASTRO ALVES,FREGUESIA/BRASILANDIA,BRASILANDIA,46.36,1,5.0,2,4.1,2.7
3,94315,EMEF PEDRO AMERICO,FREGUESIA/BRASILANDIA,FREGUESIA DO O,46.12,1,3.0,1,4.4,2.8
4,19351,"EMEF MARILI DIAS, PROFA",PIRITUBA,ANHANGUERA,48.58,1,3.0,1,4.1,2.9
...,...,...,...,...,...,...,...,...,...,...
545,93912,"EMEF CARLOS PASQUALE, PROF.",SAO MIGUEL,ITAIM PAULISTA,53.12,3,6.0,6,4.9,5.8
546,95125,EMEF BARTOLOMEU LOURENCO DE GUSMAO,ITAQUERA,CARRAO,54.34,3,3.0,5,5.0,5.8
547,93173,"EMEF JOAQUIM CANDIDO DE AZEVEDO MARQUES, DES.",SANTO AMARO,SANTO AMARO,54.80,3,3.0,5,5.3,5.9
548,92690,"EMEF AMORIM LIMA, DES.",BUTANTA,BUTANTA,57.80,3,3.0,5,5.9,6.1
549,108,"EMEF JOSE ERMIRIO DE MORAES, SEN.",SAO MIGUEL,JARDIM HELENA,48.15,1,3.0,1,4.8,6.8

In [174]:
#Media e Mediana  do ano  2023
media_inicial = df_2023["IDEP_INICIAL"].mean()
media_final = df_2023["IDEP_FINAL"].mean()

print(f"Média do IDEP_INICIAL de 2023: {media_inicial:.2f}")
print(f"Média do IDEP_FINAL de 2023: {media_final:.2f}")

#Mediana
mediana_inicial = df_2023["IDEP_INICIAL"].median()
mediana_final = df_2023["IDEP_FINAL"].median()

print(f"Mediana do IDEP_INICIAL de 2023: {mediana_inicial:.2f}")
print(f"Mediana do IDEP_FINAL de 2023: {mediana_final:.2f}")

Média do IDEP_INICIAL de 2023: 4.60
Média do IDEP_FINAL de 2023: 4.52
Mediana do IDEP_INICIAL de 2023: 4.60
Mediana do IDEP_FINAL de 2023: 4.50

In [18]:
# Calculando a diferença entre o IDEP INCIAL e IDEP FINAL de 2023
tabela_2023 = df_2023.groupby("Faixa").agg({
    "IDEP_INICIAL": ["mean", "median", "std"],
    "IDEP_FINAL": ["mean", "median", "std"],
    
}).round(2)

display(tabela_2023)

      IDEP_INICIAL              IDEP_FINAL
              mean median   std       mean median   std
Faixa
 -            3.70    3.7   NaN       4.20    4.2   NaN
 -            4.20    4.2   NaN       4.50    4.5   NaN
1             4.42    4.4  0.48       4.33    4.3  0.53
2             4.38    4.3  0.49       4.23    4.3  0.48
3             4.69    4.7  0.47       4.59    4.6  0.50
4             4.55    4.6  0.51       4.49    4.6  0.64
5             4.92    5.0  0.61       4.94    5.0  0.55
6             4.96    4.9  0.40       4.70    4.7  0.63

In [175]:
#Media e Mediana  da minha base 2024 

media_inicial_2024 = df_2024["IDEP_INICIAL"].mean()
media_final_2024= df_2024["IDEP_FINAL"].mean()
print(f"Média do IDEP_INICIAL de 2024: {media_inicial_2024:.2f}")
print(f"Média do IDEP_FINA de 2024: {media_final_2024:.2f}")

Média do IDEP_INICIAL de 2024: 5.16
Média do IDEP_FINA de 2024: 4.51

In [176]:
#Media , Mediana e desvio padrao de 2024 

tabela_2024 = df_2024.groupby("Faixa").agg({
    "IDEP_INICIAL": ["mean", "median", "std"],
    "IDEP_FINAL": ["mean", "median", "std"],
    
}).round(2)

display(tabela_2024)

      IDEP_INICIAL              IDEP_FINAL
              mean median   std       mean median   std
Faixa
1             4.92    4.8  0.59       4.26    4.3  0.50
2             4.94    4.9  0.68       4.21    4.2  0.55
3             5.25    5.2  0.63       4.63    4.6  0.46
4             5.10    5.0  0.75       4.53    4.6  0.57
5             5.53    5.5  0.58       4.86    4.9  0.57
6             5.45    5.5  0.56       4.79    4.8  0.50
 -            5.90    5.9   NaN       4.20    4.2   NaN
 -            5.30    5.3   NaN       3.90    3.9   NaN
-             4.90    4.9   NaN       5.00    5.0   NaN

In [190]:
df_2023["Faixa_NSE"] = pd.cut(
    df_2023["NSE"],
    bins=[0, 40, 50, 60, 70, 100],
    labels=["Muito baixo", "Baixo", "Médio", "Médio alto", "Alto"]
)

In [194]:
#Criando as Colunas para dentro da tabela 2024
df_2024["evolucao_IDEP"] = (df_2024["IDEP_FINAL"] - df_2024["IDEP_INICIAL"]).round(2)

condicoes = [
    df_2024["evolucao_IDEP"] >= 0.5,
    (df_2024["evolucao_IDEP"] >= 0.2) & (df_2024["evolucao_IDEP"] < 0.5),
    (df_2024["evolucao_IDEP"] > -0.2) & (df_2024["evolucao_IDEP"] < 0.2),
    (df_2024["evolucao_IDEP"] >= -0.5) & (df_2024["evolucao_IDEP"] <= -0.2),
    df_2024["evolucao_IDEP"] < -0.5
]

categorias = [
    "Avanço significativo",
    "Avanço moderado",
    "Estabilidade",
    "Declínio moderado",
    "Declínio significativo"
]

df_2024["categoria_evolucao"] = np.select(condicoes, categorias, default="Sem classificação")

df_2024["crescimento_percentual"] = df_2024["crescimento_percentual"].round(2)

C:\Users\igor_\AppData\Local\Temp\ipykernel_4348\4101227371.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2024["evolucao_IDEP"] = (df_2024["IDEP_FINAL"] - df_2024["IDEP_INICIAL"]).round(2)
C:\Users\igor_\AppData\Local\Temp\ipykernel_4348\4101227371.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2024["categoria_evolucao"] = np.select(condicoes, categorias, default="Sem classificação")
C:\Users\igor_\AppData\Local\Temp\ipykernel_4348\4101227371.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2024["crescimento_percentual"] = df_2024["crescimento_percentual"].round(2)

In [197]:

#Crianndo Novas colunas de Metrica de
df_2023["evolucao_IDEP"] = df_2023["IDEP_FINAL"] - df_2023["IDEP_INICIAL"]

condicoes = [
    df_2023["evolucao_IDEP"] >= 0.5,
    (df_2023["evolucao_IDEP"] >= 0.2) & (df_2023["evolucao_IDEP"] < 0.5),
    (df_2023["evolucao_IDEP"] > -0.2) & (df_2023["evolucao_IDEP"] < 0.2),
    (df_2023["evolucao_IDEP"] >= -0.5) & (df_2023["evolucao_IDEP"] <= -0.2),
    df_2023["evolucao_IDEP"] < -0.5
]

categorias = [
    "Avanço significativo",
    "Avanço moderado",
    "Estabilidade",
    "Declínio moderado",
    "Declínio significativo"
]

df_2023["categoria_evolucao"] = np.select(condicoes, categorias, default="Sem classificação")
df_2023["crescimento_percentual"] = df_2024["crescimento_percentual"].round(3)

display(df_2023)

,Cod_Esc,Escola,Diretoria,Distrito,NSE,Grupo,ICG,Faixa,IDEP_INICIAL,IDEP_FINAL,Faixa_NSE,evolucao_IDEP,categoria_evolucao,crescimento_absoluto,crescimento_percentual
0,92762,EMEF JOAO XXIII,BUTANTA,RAPOSO TAVARES,49.82,2,6.0,4,4.0,2.3,Baixo,-1.7,Declínio significativo,-1.7,-32.35
1,94196,EMEF ERICO VERISSIMO,FREGUESIA/BRASILANDIA,FREGUESIA DO O,50.00,2,3.0,3,4.4,2.7,Baixo,-1.7,Declínio significativo,-1.7,-40.00
2,94269,EMEF CASTRO ALVES,FREGUESIA/BRASILANDIA,BRASILANDIA,46.36,1,5.0,2,4.1,2.7,Baixo,-1.4,Declínio significativo,-1.4,-35.71
3,94315,EMEF PEDRO AMERICO,FREGUESIA/BRASILANDIA,FREGUESIA DO O,46.12,1,3.0,1,4.4,2.8,Baixo,-1.6,Declínio significativo,-1.6,-55.56
4,19351,"EMEF MARILI DIAS, PROFA",PIRITUBA,ANHANGUERA,48.58,1,3.0,1,4.1,2.9,Baixo,-1.2,Declínio significativo,-1.2,-53.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545,93912,"EMEF CARLOS PASQUALE, PROF.",SAO MIGUEL,ITAIM PAULISTA,53.12,3,6.0,6,4.9,5.8,Médio,0.9,Avanço significativo,0.9,-3.33
546,95125,EMEF BARTOLOMEU LOURENCO DE GUSMAO,ITAQUERA,CARRAO,54.34,3,3.0,5,5.0,5.8,Médio,0.8,Avanço significativo,0.8,NaN
547,93173,"EMEF JOAQUIM CANDIDO DE AZEVEDO MARQUES, DES.",SANTO AMARO,SANTO AMARO,54.80,3,3.0,5,5.3,5.9,Médio,0.6,Avanço significativo,0.6,NaN
548,92690,"EMEF AMORIM LIMA, DES.",BUTANTA,BUTANTA,57.80,3,3.0,5,5.9,6.1,Médio,0.2,Estabilidade,0.2,NaN
549,108,"EMEF JOSE ERMIRIO DE MORAES, SEN.",SAO MIGUEL,JARDIM HELENA,48.15,1,3.0,1,4.8,6.8,Baixo,2.0,Avanço significativo,2.0,NaN

In [180]:
#Quantide de escola por cada Distrito e diretoria de 2023

df_distrito=df_2023.groupby("Distrito").size()
df_diretoria =df_2023.groupby("Diretoria").size()

display(df_distrito)
display(df_diretoria)

Distrito
AGUA RASA        4
ANHANGUERA       7
ARICANDUVA       4
ARTUR ALVIM      6
BELA VISTA       1
                ..
VILA MARIANA     1
VILA MATILDE     7
VILA MEDEIROS    5
VILA PRUDENTE    4
VILA SONIA       5
Length: 86, dtype: int64

Diretoria
BUTANTA                  33
CAMPO LIMPO              68
CAPELA DO SOCORRO        34
FREGUESIA/BRASILANDIA    38
GUAIANASES               36
IPIRANGA                 36
ITAQUERA                 30
JACANA/TREMEMBE          38
PENHA                    39
PIRITUBA                 60
SANTO AMARO              34
SAO MATEUS               52
SAO MIGUEL               52
dtype: int64

In [198]:
df_2023['crescimento_absoluto'] = df_2023['IDEP_FINAL'] - df_2023['IDEP_INICIAL']
df_2023['crescimento_percentual'] = (df_2023['crescimento_absoluto'] / df_2023['IDEP_INICIAL']) * 100

In [199]:
#As top 10 Escolas Mais Avaliadas de 2023 
top5_escolas = (
    df_2023
    .sort_values("IDEP_FINAL", ascending=False)
    .head(10)
)

display(
    top5_escolas[
        ["Diretoria", "Escola", "IDEP_INICIAL", "IDEP_FINAL", "crescimento_percentual"]
    ].round(2)
)

,Diretoria,Escola,IDEP_INICIAL,IDEP_FINAL,crescimento_percentual
549,SAO MIGUEL,"EMEF JOSE ERMIRIO DE MORAES, SEN.",4.8,6.8,41.67
548,BUTANTA,"EMEF AMORIM LIMA, DES.",5.9,6.1,3.39
547,SANTO AMARO,"EMEF JOAQUIM CANDIDO DE AZEVEDO MARQUES, DES.",5.3,5.9,11.32
545,SAO MIGUEL,"EMEF CARLOS PASQUALE, PROF.",4.9,5.8,18.37
544,CAMPO LIMPO,CEU EMEF CASA BLANCA,5.3,5.8,9.43
546,ITAQUERA,EMEF BARTOLOMEU LOURENCO DE GUSMAO,5.0,5.8,16.00
542,JACANA/TREMEMBE,"EMEF MAXIMO DE MOURA SANTOS, PROF.",5.2,5.7,9.62
541,PIRITUBA,"EMEF AMADEU MENDES, PROF.",5.6,5.7,1.79
538,BUTANTA,"EMEF OLAVO PEZZOTTI, PROF.",5.4,5.7,5.56
539,SANTO AMARO,"EMEF LAERTE RAMOS DE CARVALHO, PROF.",5.1,5.7,11.76

In [200]:
 #As Top 1piores escolas de 2023


top10_piores = (
    df_2023
    .sort_values("IDEP_FINAL", ascending=True)
    .head(10)
)

display(
    top10_piores[
        [ "Diretoria", "Escola", "IDEP_INICIAL", "IDEP_FINAL", "crescimento_percentual"]
    ].round(2)
)

,Diretoria,Escola,IDEP_INICIAL,IDEP_FINAL,crescimento_percentual
0,BUTANTA,EMEF JOAO XXIII,4.0,2.3,-42.50
1,FREGUESIA/BRASILANDIA,EMEF ERICO VERISSIMO,4.4,2.7,-38.64
2,FREGUESIA/BRASILANDIA,EMEF CASTRO ALVES,4.1,2.7,-34.15
3,FREGUESIA/BRASILANDIA,EMEF PEDRO AMERICO,4.4,2.8,-36.36
4,PIRITUBA,"EMEF MARILI DIAS, PROFA",4.1,2.9,-29.27
5,CAMPO LIMPO,CEU EMEF PARAISOPOLIS,3.8,3.0,-21.05
6,FREGUESIA/BRASILANDIA,"EMEF AROLDO DE AZEVEDO, PROF.",4.4,3.0,-31.82
7,GUAIANASES,"EMEF CAIO SERGIO POMPEU DE TOLEDO, DEP.",4.8,3.2,-33.33
8,SAO MATEUS,EMEF JARDIM DAS LARANJEIRAS,5.0,3.2,-36.00
9,GUAIANASES,"EMEF ANNA LAMBERGA ZEGLIO, VER.",3.6,3.3,-8.33

In [184]:
df_2024['crescimento_absoluto'] = df_2024['IDEP_FINAL'] - df_2024['IDEP_INICIAL']
df_2024['crescimento_percentual'] = (df_2024['crescimento_absoluto'] / df_2024['IDEP_INICIAL']) * 100

C:\Users\igor_\AppData\Local\Temp\ipykernel_4348\921434383.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2024['crescimento_absoluto'] = df_2024['IDEP_FINAL'] - df_2024['IDEP_INICIAL']
C:\Users\igor_\AppData\Local\Temp\ipykernel_4348\921434383.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2024['crescimento_percentual'] = (df_2024['crescimento_absoluto'] / df_2024['IDEP_INICIAL']) * 100

In [201]:
#As 10 Melhores Escolas de 2024  por distrito 


top10_piores = (
    df_2024
    .sort_values("IDEP_FINAL", ascending=False)
    .head(10)
)

display(
    top10_piores[
        [ "Diretoria", "Escola", "IDEP_INICIAL", "IDEP_FINAL", "crescimento_percentual"]
    ].round(2)
)

,Diretoria,Escola,IDEP_INICIAL,IDEP_FINAL,crescimento_percentual
544,ITAQUERA,EMEF SERGIO MILLIET,5.4,5.8,7.41
545,SAO MIGUEL,EMEF JOSE ERMIRIO DE MORAES. SEN.,6.0,5.8,-3.33
542,ITAQUERA,EMEF KENNEDY. PRES.,5.6,5.7,1.79
538,SANTO AMARO,EMEF LAERTE RAMOS DE CARVALHO. PROF.,5.9,5.7,-3.39
543,PIRITUBA,EMEF JOSE MARIA PINTO DUARTE. TTE.,6.2,5.7,-8.06
539,SAO MATEUS,EMEF HENRIQUE SOUZA FILHO - HENFIL,5.2,5.7,9.62
540,PIRITUBA,EMEF LIBERATO BITTENCOURT. GEN.,6.0,5.7,-5.00
541,JACANA/TREMEMBE,EMEF HELENA LOMBARDI BRAGA. PROFA.,5.9,5.7,-3.39
534,PIRITUBA,EMEF JULIO DE OLIVEIRA,5.1,5.6,9.80
532,SANTO AMARO,EMEF JOAQUIM CANDIDO DE AZEVEDO MARQUES. DES.,6.1,5.6,-8.20

In [202]:
#Segundo a base de 2024
top10_piores = (
    df_2024
    .sort_values("IDEP_FINAL", ascending=True)
    .head(10)
)

display(
    top10_piores[
        [ "Diretoria", "Escola", "IDEP_INICIAL", "IDEP_FINAL", "crescimento_percentual"]
    ].round(2))

,Diretoria,Escola,IDEP_INICIAL,IDEP_FINAL,crescimento_percentual
0,JACANA/TREMEMBE,EMEF PAULO CARNEIRO THOMAZ ALVES. GEN.,3.4,2.3,-32.35
1,SAO MATEUS,EMEF ARLINDO CAETANO FILHO. PROF.,4.5,2.7,-40.00
2,FREGUESIA/BRASILANDIA,EMEF JOAO AMOS COMENIUS,4.2,2.7,-35.71
3,CAPELA DO SOCORRO,EMEF DAMIAO. FREI,6.3,2.8,-55.56
4,PIRITUBA,EMEF MARIO LAGO,6.2,2.9,-53.23
5,FREGUESIA/BRASILANDIA,EMEF MILTOM CAMPOS. SEN.,3.6,3.0,-16.67
6,SANTO AMARO,EMEF ARY PARREIRAS. ALM.,4.7,3.0,-36.17
7,GUAIANASES,EMEF ANNA LAMBERGA ZEGLIO. VER.,4.3,3.2,-25.58
8,JACANA/TREMEMBE,EMEFM ANTONIO SAMPAIO. VER.,4.1,3.2,-21.95
9,FREGUESIA/BRASILANDIA,EMEF CECILIA MORAES DE VASCONCELOS. PROFA.,3.6,3.3,-8.33

In [203]:
tabela_faixa_2024 = (
    df_2023
    .groupby(["Faixa", "Distrito"])
    .agg({
        "NSE": "mean",
        "IDEP_FINAL": "mean"
    })
    .round(2)
    .reset_index()
)

display(tabela_faixa_2024)

    Faixa      Distrito    NSE  IDEP_FINAL
0       -   BRASILANDIA    NaN         4.2
1      -           PARI    NaN         4.5
2       1    ANHANGUERA  48.25         3.7
3       1         BELEM  48.31         4.1
4       1   BRASILANDIA  48.09         3.9
..    ...           ...    ...         ...
266     6    SAO MIGUEL  53.86         5.1
267     6       TATUAPE  52.58         3.6
268     6   VILA CURUCA  52.61         5.5
269     6  VILA FORMOSA  52.87         5.3
270     6  VILA MATILDE  53.29         5.1

[271 rows x 4 columns]

In [204]:
#De 2024 
tabela_faixa = (
    df_2024
    .groupby(["Faixa", "Distrito"])
    .agg({
        "NSE": "mean",
        "IDEP_FINAL": "mean"
    })
    .round(2)
    .reset_index()
)

display(tabela_faixa)

    Faixa           Distrito    NSE  IDEP_FINAL
0       1         ANHANGUERA  48.25        4.55
1       1              BELEM  48.31        4.70
2       1        BRASILANDIA  48.15        3.81
3       1       CACHOEIRINHA  48.39        4.40
4       1         CAMPO BELO  48.51        4.30
..    ...                ...    ...         ...
265     6       VILA FORMOSA  52.87        5.70
266     6       VILA MATILDE  53.29        4.60
267     -        BRASILANDIA    NaN        4.20
268    -                PARI    NaN        3.90
269     -  CIDADE TIRADENTES    NaN        5.00

[270 rows x 4 columns]

In [205]:
media_idep_icg = df.groupby('ICG')['IDEP_FINAL'].mean().round(2)
print(media_idep_icg)

ICG
 -     4.60
1       NaN
2      4.60
3      4.57
4      4.54
5      4.43
6      4.35
Name: IDEP_FINAL, dtype: float64

In [206]:
df_2023.to_excel("idep_2023_tratado.xlsx", index=False)

In [207]:
#Hora do Salvamento 
df_2023.to_excel("idep_2023_tratado.xlsx", index=False)
df_2024.to_excel("idep_2024_tratado.xlsx", index=False)